<?php

declare(strict_types=1);

namespace Larapilot\Services\Boogle;

use Larapilot\Services\ConfigService;
use Larapilot\Support\AtomicFile;
use Larapilot\Support\FileLock;
use Symfony\Component\Yaml\Yaml;

/**
 * What was decided about each error Boogle recorded, kept in
 * `.larapilot/boogle.yaml`: the spec that fixes it, or the reason it is
 * left as it is.
 *
 * A decision is about a bug, not about one time it happened: it is kept
 * under what the occurrences of one bug share — the exception, the file,
 * the line — so the next time it happens it is not handed over again.
 *
 * The file is committed. It holds the class, the place in the code, and
 * the decision: never a credential, never the message, the user, or the
 * request of an occurrence.
 */
class BoogleLedger
{
    public const IN_BACKLOG = 'in_backlog';

    public const IGNORED = 'ignored';

    public function __construct(protected ConfigService $config) {}

    public function path(): string
    {
        return $this->config->absolutePath('.larapilot/boogle.yaml');
    }

    public function relativePath(): string
    {
        return '.larapilot/boogle.yaml';
    }

    /**
     * Every decision, keyed by the key of the error.
     *
     * @return array<string, array<string, mixed>>
     */
    public function all(): array
    {
        $errors = $this->read()['errors'] ?? [];
        $decisions = [];

        foreach (is_array($errors) ? $errors : [] as $key => $decision) {
            if (is_array($decision)) {
                $decisions[(string) $key] = $decision;
            }
        }

        return $decisions;
    }

    /**
     * @param  array<string, mixed>  $decision
     * @param  array<string, mixed>  $project
     */
    public function record(string $key, array $decision, array $project = []): void
    {
        $this->change(function (array $state) use ($key, $decision, $project): array {
            $state['errors'][$key] = array_filter(
                array_merge($state['errors'][$key] ?? [], $decision, ['at' => now()->toIso8601String()]),
                static fn (mixed $value): bool => $value !== null && $value !== '' && $value !== []
            );

            if ($project !== []) {
                $state['project'] = $project;
            }

            return $state;
        });
    }

    /**
     * What is known about an error changes, the decision does not: the
     * codes Boogle gave to its occurrences, or the day it was closed there.
     *
     * @param  array<string, mixed>  $facts
     */
    public function note(string $key, array $facts): void
    {
        $this->change(function (array $state) use ($key, $facts): array {
            if (isset($state['errors'][$key])) {
                $state['errors'][$key] = array_merge($state['errors'][$key], $facts);
            }

            return $state;
        });
    }

    public function forget(string $key): void
    {
        $this->change(function (array $state) use ($key): array {
            unset($state['errors'][$key]);

            return $state;
        });
    }

    /**
     * @param  callable(array<string, mixed>): array<string, mixed>  $change
     */
    protected function change(callable $change): void
    {
        FileLock::withLock($this->path(), function () use ($change): void {
            $state = $this->read();
            $state['errors'] = is_array($state['errors'] ?? null) ? $state['errors'] : [];
            $state = $change($state);

            ksort($state['errors'], SORT_STRING);
            $state['updated_at'] = now()->toIso8601String();

            AtomicFile::write(
                $this->path(),
                "# Generated by Larapilot (php artisan larapilot:errors-link).\n"
                ."# What was decided about each error Boogle recorded: the spec that fixes it, or why it is left as it is.\n"
                ."# Safe to commit: the class, the place in the code and the decision. Never a credential, a message, a user, a request.\n"
                .Yaml::dump($state, 6, 2, Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK)
            );
        });
    }

    /**
     * @return array<string, mixed>
     */
    protected function read(): array
    {
        if (! is_file($this->path())) {
            return ['errors' => []];
        }

        try {
            $parsed = Yaml::parseFile($this->path());
        } catch (\Throwable) {
            return ['errors' => []];
        }

        return is_array($parsed) ? $parsed : ['errors' => []];
    }
}
