<?php

declare(strict_types=1);

namespace Larapilot\Services\Tracker;

use Larapilot\Services\ConfigService;
use Larapilot\Support\AtomicFile;
use Larapilot\Support\FileLock;
use Symfony\Component\Yaml\Yaml;

/**
 * The spec ↔ remote-record mapping, kept in `.larapilot/tracker.yaml`.
 *
 * The file is committed so a team shares one mapping instead of each machine
 * creating duplicate cards. It therefore holds identifiers only — never a
 * credential.
 *
 * State is keyed by provider so switching trackers (or switching back) does
 * not lose the previous mapping.
 */
class TrackerLinkStore
{
    /**
     * @var array<string, mixed>|null
     */
    protected ?array $state = null;

    public function __construct(protected ConfigService $config) {}

    public function path(): string
    {
        return $this->config->absolutePath('.larapilot/tracker.yaml');
    }

    public function exists(): bool
    {
        return is_file($this->path());
    }

    /**
     * Every link for a provider, keyed by spec code.
     *
     * @return array<string, array<string, mixed>>
     */
    public function all(string $provider): array
    {
        $providers = $this->state()['providers'] ?? [];

        if (! is_array($providers)) {
            return [];
        }

        $links = $providers[$provider] ?? [];

        if (! is_array($links)) {
            return [];
        }

        $normalized = [];

        foreach ($links as $code => $link) {
            if (is_string($code) && is_array($link)) {
                $normalized[$code] = $link;
            }
        }

        return $normalized;
    }

    /**
     * @return array<string, mixed>|null
     */
    public function find(string $provider, string $code): ?array
    {
        return $this->all($provider)[$code] ?? null;
    }

    public function ref(string $provider, string $code): ?RemoteRef
    {
        $link = $this->find($provider, $code);

        return $link === null ? null : RemoteRef::fromState($link);
    }

    /**
     * @param  array<string, mixed>  $link
     */
    public function put(string $provider, string $code, array $link): void
    {
        $state = $this->state();
        $providers = is_array($state['providers'] ?? null) ? $state['providers'] : [];
        $links = is_array($providers[$provider] ?? null) ? $providers[$provider] : [];

        $links[$code] = $link;
        ksort($links);

        $providers[$provider] = $links;
        $state['providers'] = $providers;

        $this->state = $state;
    }

    public function forget(string $provider, string $code): void
    {
        $state = $this->state();
        $providers = is_array($state['providers'] ?? null) ? $state['providers'] : [];
        $links = is_array($providers[$provider] ?? null) ? $providers[$provider] : [];

        unset($links[$code]);

        $providers[$provider] = $links;
        $state['providers'] = $providers;

        $this->state = $state;
    }

    /**
     * Run a mutation with the file locked, re-reading first so two syncs
     * cannot drop each other's links, and persisting once at the end.
     *
     * @template T
     *
     * @param  callable(): T  $callback
     * @return T
     */
    public function transaction(string $provider, callable $callback): mixed
    {
        return FileLock::withLock($this->path(), function () use ($provider, $callback): mixed {
            $this->state = null;

            $result = $callback();

            $this->save($provider);

            return $result;
        });
    }

    public function save(string $provider): void
    {
        $state = $this->state();
        $state['provider'] = $provider;
        $state['updated_at'] = now()->toIso8601String();

        AtomicFile::write(
            $this->path(),
            "# Generated by Larapilot (php artisan larapilot:tracker-push).\n"
            ."# Maps backlog specs to records in the configured project tracker.\n"
            ."# Safe to commit: identifiers only, never API credentials.\n"
            .Yaml::dump($state, 6, 2, Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK)
        );

        $this->state = $state;
    }

    /**
     * @return array<string, mixed>
     */
    protected function state(): array
    {
        if ($this->state !== null) {
            return $this->state;
        }

        if (! is_file($this->path())) {
            return $this->state = ['providers' => []];
        }

        $parsed = Yaml::parseFile($this->path());

        return $this->state = is_array($parsed) ? $parsed : ['providers' => []];
    }
}
